#!/usr/bin/env python3
"""
Report Generator — turn overlap detection JSON into human-readable
markdown reports or LLM prompt payloads for risk assessment.

Usage:
    python report_generator.py overlap_results.json --output report.md
    python report_generator.py overlap_results.json --llm-prompt > prompt.txt
    python report_generator.py overlap_results.json --output report.md --llm-prompt > prompt.txt
"""

import argparse
import json
import sys
from collections import defaultdict


def load_results(path):
    """Load the JSON output from find_overlaps.py."""
    with open(path) as f:
        return json.load(f)


# ── Markdown report ──────────────────────────────────────────────────────────

def generate_markdown(data):
    """Generate a human-readable markdown report from overlap findings."""
    lines = []
    lines.append(f"# GDS Overlap Report — {data['gds_file']}")
    lines.append(f"**Cell:** {data['cell']}\n")

    summary = data["summary"]
    lines.append("## Summary\n")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Pad regions analysed | {summary['total_pad_regions']} |")
    lines.append(f"| RDL regions analysed | {summary['total_rdl_regions']} |")
    lines.append(f"| Total overlaps found | {summary['total_overlaps']} |")
    lines.append("")

    # Config info
    cfg = data["config"]
    lines.append("## Layer Configuration\n")
    lines.append(f"- **Pad layers:** {cfg['pad_layers']}")
    lines.append(f"- **RDL layers:** {cfg['rdl_layers']}")
    lines.append(f"- **Check layers:**")
    for cl in cfg["check_layers"]:
        lines.append(f"  - {cl['name']} (layer {cl['layer']})")
    lines.append(f"- **Min overlap area:** {cfg['min_overlap_area']}")
    lines.append("")

    if not data["findings"]:
        lines.append("## Findings\n")
        lines.append("No overlaps detected. All pad/RDL regions are clear of check-layer geometries.\n")
        return "\n".join(lines)

    # Group findings by region type, then by check layer
    by_type = defaultdict(lambda: defaultdict(list))
    for f in data["findings"]:
        by_type[f["region_type"]][f["check_layer"]].append(f)

    for region_type in ["pad", "rdl"]:
        if region_type not in by_type:
            continue
        label = "Pad" if region_type == "pad" else "RDL"
        lines.append(f"## {label} Region Overlaps\n")

        for layer_name, overlaps in sorted(by_type[region_type].items()):
            lines.append(f"### Layer: {layer_name}\n")
            lines.append(f"**{len(overlaps)} overlap(s) found**\n")
            lines.append("| # | Region Bounds | Overlap Area | % of Region | % of Geometry | Geometry Bounds |")
            lines.append("|---|---------------|-------------|-------------|---------------|-----------------|")
            for i, ov in enumerate(overlaps, 1):
                rb = ov["region_bounds"]
                gb = ov["geometry_bounds"]
                lines.append(
                    f"| {i} "
                    f"| ({rb[0]:.1f}, {rb[1]:.1f})..({rb[2]:.1f}, {rb[3]:.1f}) "
                    f"| {ov['overlap_area']:.2f} "
                    f"| {ov['overlap_pct_of_region']:.1f}% "
                    f"| {ov['overlap_pct_of_geometry']:.1f}% "
                    f"| ({gb[0]:.1f}, {gb[1]:.1f})..({gb[2]:.1f}, {gb[3]:.1f}) |"
                )
            lines.append("")

    lines.append("---\n*Generated by gds-layout-explorer*\n")
    return "\n".join(lines)


# ── LLM prompt payload ──────────────────────────────────────────────────────

def generate_llm_prompt(data):
    """
    Generate a structured prompt for an LLM to perform risk assessment
    on the overlap findings.
    """
    parts = []

    parts.append("You are an IC packaging and layout reliability expert. "
                  "Analyze the following overlap findings from a GDSII layout "
                  "and assess the risk each one poses to packaging reliability.\n")

    parts.append("## Context\n")
    parts.append(f"- **Chip:** {data['gds_file']} (cell: {data['cell']})")
    parts.append(f"- **Total overlaps found:** {data['summary']['total_overlaps']}")
    parts.append(f"- **Pad regions:** {data['summary']['total_pad_regions']}")
    parts.append(f"- **RDL regions:** {data['summary']['total_rdl_regions']}")
    parts.append("")

    parts.append("## Known Failure Modes to Consider\n")
    parts.append("- **Solder reflow shift:** Structures under pads can shift ~1-5% "
                  "during reflow. Poly resistors are especially sensitive.")
    parts.append("- **Stress cracking:** Mechanical stress from ball bonding or "
                  "thermal cycling can crack underlying dielectrics or poly.")
    parts.append("- **Electromigration:** High current density paths under pads "
                  "can accelerate electromigration failures.")
    parts.append("- **Oxide cracking:** Probe marks and wire bonding can cause "
                  "oxide damage that propagates to underlying structures.")
    parts.append("- **Thermal mismatch:** CTE differences between bump materials "
                  "and underlying layers create stress concentrations.")
    parts.append("")

    parts.append("## Overlap Findings\n")

    if not data["findings"]:
        parts.append("No overlaps were detected. All pad/RDL regions appear clear.")
    else:
        # Group by region type
        by_type = defaultdict(list)
        for f in data["findings"]:
            by_type[f["region_type"]].append(f)

        for region_type in ["pad", "rdl"]:
            if region_type not in by_type:
                continue
            label = "PAD" if region_type == "pad" else "RDL"
            parts.append(f"### {label} Region Overlaps\n")
            for i, ov in enumerate(by_type[region_type], 1):
                parts.append(f"**Finding {i}:**")
                parts.append(f"  - Layer: {ov['check_layer']} ({ov['check_layer_number']})")
                parts.append(f"  - Overlap area: {ov['overlap_area']}")
                parts.append(f"  - Overlap as % of {region_type} region: {ov['overlap_pct_of_region']}%")
                parts.append(f"  - Overlap as % of geometry: {ov['overlap_pct_of_geometry']}%")
                parts.append(f"  - Region bounds: {ov['region_bounds']}")
                parts.append(f"  - Geometry bounds: {ov['geometry_bounds']}")
                parts.append("")

    parts.append("## Your Task\n")
    parts.append("For each finding above:")
    parts.append("1. Assign a **risk level**: HIGH, MEDIUM, or LOW")
    parts.append("2. Explain **why** this overlap is or isn't concerning, "
                  "referencing specific failure modes")
    parts.append("3. Provide a **recommendation** (e.g., move the structure, "
                  "add a keep-out zone, acceptable as-is, needs further analysis)")
    parts.append("")
    parts.append("Finally, provide an **overall assessment** of the layout's "
                  "packaging risk and any general recommendations.")

    return "\n".join(parts)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate reports from GDS overlap detection results."
    )
    parser.add_argument("results_file", help="Path to the JSON results from find_overlaps.py")
    parser.add_argument("--output", default=None, help="Write markdown report to this file")
    parser.add_argument("--llm-prompt", action="store_true",
                        help="Print LLM risk-assessment prompt to stdout")
    args = parser.parse_args()

    data = load_results(args.results_file)

    if not args.output and not args.llm_prompt:
        print("Error: specify --output for markdown report and/or --llm-prompt for LLM payload.")
        sys.exit(1)

    if args.output:
        md = generate_markdown(data)
        with open(args.output, "w") as f:
            f.write(md)
        print(f"Markdown report written to {args.output}", file=sys.stderr)

    if args.llm_prompt:
        prompt = generate_llm_prompt(data)
        print(prompt)


if __name__ == "__main__":
    main()
